version: "3.9"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluent
    volumes:
    - /var/lib/docker/containers:/tmp/log/containers
    - ./fluentdconfig:/fluentd/etc/
    - ./logs:/out/test.logs
    logging:
      driver: "local"
  elasticsearch:
    image: elasticsearch:7.9.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: kibana:7.9.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
