version: "3.9"
services:
  fluentd:
    container_name: fluentd
    user: root
    image: fluent/fluentd:v1.15-1
    volumes:
    - /var/lib/docker/containers:/tmp/log/containers
    - ./fluentdconfig:/fluentd/etc/
    - ./logs:/out/test.logs
    logging:
      driver: "local"
