---
 - name: Playbook with create folders
   hosts: prod_servers
   become: yes

   vars:
    text: "This file create by Ansible"

   tasks:
     - name: Create Dirs
       include: playbook4_dir.yml

     - name: Create Files
       include: playbook4_files.yml
     
       # - include: playbook4_dir.yml
       # - include: playbook4_files.yml
