- hosts: webservers
  roles:
    - common
    - nginx
  tags:
    web

- hosts: proxy
  roles:
    - common
    - nginx-proxy
  tags:
    proxy

- hosts: docker-in-docker
  roles:
    - docker
  tags:
    docker