---
- name: Loops copy files
  hosts: linux3
  become: yes

  vars:
    source_folder: ./TestFolder
    destin_folder: /var/www/html

  tasks:
    - name: copy files 
      copy: src={{ source_folder }}/{{ item }} dest={{ destin_folder }} mode=0620
      loop: 
        - "File1"
        - "File2"
        - "File3"
        - "File4"  
