---
- name: Loops playbook
  hosts: linux3
  become: yes

  tasks:
    - name: Test message
      debug: msg="This is test mesage {{ item }}"
      loop: 
        - "One"
        - "2"
        - "Test 3"
        - "SimpleFour"  

    - name: Test until loop
      shell: echo -n Test >> test.file && cat test.file
      register: output
      delay: 2
      retries: 10
      until: output.stdout.find("TestTestTestTestTest") == false

    - name: Print output variable
      debug: var=output.stdout

      #    - name: Install pkg
      #      yum: name={{ item }} state=installed
      #      loop:
      #        - python
      #        - httpd
      #        - mysql-cliend
      #        - sshd-server
