#BUG https://github.com/bitnami/containers/issues/16243

version: "3.9"
services:
  kafka-controller-1:
    container_name: kafka-controller-1
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=controller      
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9093
    - KAFKA_BROKER_ID=101
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka
  kafka-controller-2:
    container_name: kafka-controller-2
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=controller      
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9093
    - KAFKA_BROKER_ID=102
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka
  kafka-controller-3:
    container_name: kafka-controller-3
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=controller      
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=CONTROLLER://:9093
    - KAFKA_BROKER_ID=103
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka
  kafka-1:
    container_name: kafka-1-kraft
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker      
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka
  kafka-2:
    container_name: kafka-2-kraft
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker      
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_BROKER_ID=2
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka
  kafka-3:
    container_name: kafka-3-kraft
    image: 'bitnami/kafka:3.4-debian-11'
    environment:
    - KAFKA_ENABLE_KRAFT=yes
    - KAFKA_CFG_PROCESS_ROLES=broker      
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
    - KAFKA_BROKER_ID=3
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=101@kafka-controller-1:9093,102@kafka-controller-2:9093,103@kafka-controller-3:9093
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
    - kafka

networks:
  kafka:
    driver: bridge