---
- name: Test playbook
  hosts: all
  become: yes

  vars:
    mytext: "Test text text text"
 
  tasks:

  - name: Test unregister Server from loadbalancer
    shell: echo This sever {{ inventory_hostname }} was unregistered from LB, node name is {{ ansible_nodename }} >> /home/user/log.ansible.txt
    delegate_to: 127.0.0.1
  
  - name: Update DB
    shell: echo Command for update DB... 
    run_once: true #run command in one server  

  - name: Create file1
    copy:
      dest: /home/user/file1.txt
      content:
              This is some text {{ mytext }}
    delegate_to: ubuntu

  - name: Create file2
    copy:
      dest: /home/user/file2.txt
      content:
              This is some text {{ mytext }}

  - name: Reboot nodes servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0 

  - name: Wait nodes servers for come up
    wait_for:
       host: "{{ inventory_hostname }}"
       state: started
       delay: 5
       timeout: 40
    delegate_to: 127.0.0.1     
