---
- name: Install packages
  yum: 
    name: yum-utils
    state: latest

- name: Add Docker GPG key.
  yum_repository:
    name: epel
    baseurl: https://download.docker.com/linux/rhel/docker-ce.repo

- name: Install docker
  yum: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-buildx-plugin', ' docker-compose-plugin']
    state: latest

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true