#!/bin/bash

DELAY=10

while [ "$INPUT" != 0 ]; do
	clear
	cat <<- _EOF_
		1. OS Type.
		2. Free disck space.
		3. Network config.
		4. Show only IP.
		5. Users in the system.
		0. Exit.
	_EOF_
	
	read -p "Choose the item: " INPUT
		
	if [[ $INPUT =~ ^[0-5]$ ]]; then
		if [ $INPUT = 1 ]; then
			cat /etc/os-release
			sleep $DELAY
		fi

		
		if [ $INPUT = 2 ]; then
			df -h
			sleep $DELAY
		fi
	
		if [ $INPUT = 3 ]; then
			ip a
			sleep $DELAY
		fi
		
		if [ $INPUT = 4 ]; then
			ip a | grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}"
			sleep $DELAY
		fi
		
		if [ $INPUT = 5 ]; then
			cat /etc/passwd | cut -f 1 -d : | sort
			sleep $DELAY
		fi
	else
		echo "Write number of diapasone!"	
			sleep $DELAY
	fi
done


